---
- hosts:
  user: ec2-user
  become: yes
  connection: ssh

  vars:
    ansible_private_key_file: "/etc/ansible/mykeypair.pem"
    ansible_ssh_user: "ec2_user"

  tasks:
    - name: installing git
      action: yum name=git state=present
    
    - name: install webserver
      action: yum name=httpd state=present

    - name: restart web servers
      service: yum name=httpd state=restarted
      
    - name: getting code to server
      git:
        repo: ""
        dest: /var/www/html/
        version: ""




